blog/urls.py
from django.urls import path, reverse

from blog.views import HomePage, CategoryDetails, PostView, PostListsByTag, SearchResultsView, post_comment

app_name = 'blog'

urlpatterns = [
    path("", HomePage.as_view(), name='homepage'),
    path("category/<slug:slug>/", CategoryDetails.as_view(), name='category_detail'),
    path("post/<slug:slug>/", PostView.as_view(), name='post_detail'),
    path("tag/<slug:tag_slug>/", PostListsByTag.as_view(), name='posts_by_tag'),
    path("search/", SearchResultsView.as_view(), name="search_results"),
    path("<int:post_id>/comment/", post_comment, name='post_comment'),
]

newswhy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.
class Category(MPTTModel):
    name = models.CharField(max_length=50, unique=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    slug = models.SlugField(max_length=100, unique=True)

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:category_detail', kwargs={'slug': self.slug})


class PublishManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    content = models.TextField()
    image = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    objects = models.Manager()
    published = PublishManager()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    views = models.PositiveIntegerField(default=0)
    tags = TaggableManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish'])
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.slug})



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from django.forms import widgets
from .models import Comment

class SearchForm(forms.Form):
    pass
    query = forms.CharField()


class CommentForm(forms.ModelForm):
    parent_comment = forms.IntegerField(widget=forms.HiddenInput(), required=False)
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, TemplateView, View
import random
from django.core.paginator import Paginator
from .models import Category, Post, Comment
from taggit.models import Tag
from django.db.models import Q
from .forms import CommentForm
from django.views.decorators.http import require_POST
from django.shortcuts import redirect

# Create your views here.
class CategoryLists(ListView):
    model = Category
    #template_name = 'blog/categories.html'


class PostListsByTag(ListView):
    model = Post
    template_name = 'blog/posts_by_tag.html'
    context_object_name = 'posts'
    allow_empty = False
    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Tag.objects.get(slug=self.kwargs['tag_slug'])
        return context

    def get_queryset(self):
        return Post.published.filter(tags__slug=self.kwargs['tag_slug'])




class CategoryDetails(ListView):
    model = Post
    template_name = 'blog/category.html'
    context_object_name = 'posts'
    allow_empty = False
    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Category.objects.get(slug=self.kwargs['slug'])
        context['tags'] = Tag.objects.all()
        return context

    def get_queryset(self):
        # Get the specific category
        category = Category.objects.get(slug=self.kwargs['slug'])

        # Get posts from the specific category and its descendants (including parent categories)
        queryset = Post.published.filter(category__in=category.get_descendants(include_self=True)).select_related('category')
        return queryset
        #return Post.published.filter(category__slug=self.kwargs['slug']).select_related('category')


class PostView(DetailView):
    model = Post
    template_name = "blog/post_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug = self.kwargs["slug"]

        form = CommentForm()
        post = get_object_or_404(Post, slug=slug)
        post.views += 1
        post.save()
        popular_posts = Post.published.order_by('-views')[:3]
        subcategory_post_counts = {}
        root_categories = Category.objects.filter(parent__isnull=True)

        subcategory_post_counts = {}

        for root_category in root_categories:
            subcategories = root_category.get_descendants(include_self=True)

            for subcategory in subcategories:
                post_count = Post.objects.filter(category=subcategory).count()
                subcategory_post_counts[subcategory] = post_count
        comments = post.comments.all()

        context['post'] = post
        context['comments'] = comments
        context['form'] = form
        context['popular_posts'] = popular_posts
        context['subcategory_post_counts'] = subcategory_post_counts

        return context

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        self.object = self.get_object()
        context = super().get_context_data(**kwargs)

        post = Post.objects.filter(slug=self.kwargs['slug'])[0]
        comments = post.comments.all()

        context['post'] = post
        context['comments'] = comments
        context['form'] = form

        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            body = form.cleaned_data['body']

            comment = Comment.objects.create(
                name=name, email=email, body=body, post=post
            )

            form = CommentForm()
            context['form'] = form
            return self.render_to_response(context=context)

        return self.render_to_response(context=context)


class HomePage(TemplateView):
    template_name = 'blog/homepage.html'

    def get_context_data(self, **kwargs):
        items = list(Post.objects.all())

        # change 3 to how many random items you want
        random_items = random.sample(items, 5)
        context = super().get_context_data(**kwargs)
        #context['categories'] = Category.objects.all()
        context['posts'] = Post.published.all()
        context['random_5_posts'] = random_items
        return context


class SearchResultsView(ListView):
    model = Post
    template_name = 'blog/search_results.html'
    context_object_name = 'posts'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get("q")
        return context

    def get_queryset(self):
        query = self.request.GET.get("q")
        return Post.published.filter(Q(title__icontains=query) | Q(content__icontains=query))


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None

    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()

    return render(request, 'blog/comment.html', {'post': post, 'form': form, 'comment': comment})

blog/templates/blog/_footer.html
{% load blog_tags %}
<footer class="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="widget">
                    <h3 class="mb-4">About</h3>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                </div> <!-- /.widget -->
                <div class="widget">
                    <h3>Social</h3>
                    <ul class="list-unstyled social">
                        <li><a href="#"><span class="icon-instagram"></span></a></li>
                        <li><a href="#"><span class="icon-twitter"></span></a></li>
                        <li><a href="#"><span class="icon-facebook"></span></a></li>
                        <li><a href="#"><span class="icon-linkedin"></span></a></li>
                        <li><a href="#"><span class="icon-pinterest"></span></a></li>
                        <li><a href="#"><span class="icon-dribbble"></span></a></li>
                    </ul>
                </div> <!-- /.widget -->
            </div> <!-- /.col-lg-4 -->
            <div class="col-lg-4 ps-lg-5">
                <div class="widget">
                    <h3 class="mb-4">Company</h3>
                    <ul class="list-unstyled float-start links">
                        <li><a href="#">About us</a></li>
                        <li><a href="#">Services</a></li>
                        <li><a href="#">Vision</a></li>
                        <li><a href="#">Mission</a></li>
                        <li><a href="#">Terms</a></li>
                        <li><a href="#">Privacy</a></li>
                    </ul>
                    <ul class="list-unstyled float-start links">
                        <li><a href="#">Partners</a></li>
                        <li><a href="#">Business</a></li>
                        <li><a href="#">Careers</a></li>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">Creative</a></li>
                    </ul>
                </div> <!-- /.widget -->
            </div> <!-- /.col-lg-4 -->
            <div class="col-lg-4">
                <div class="widget">
                    <h3 class="mb-4">Recent Post Entry</h3>
                    <div class="post-entry-footer">
                    {% recent_posts as r_posts %}
                        <ul>
                            {% for post in r_posts %}
                                <li>
                                    <a href="{{ post.get_absolute_url }}">
                                        <img src="{{ post.image.url }}" alt="Image placeholder" class="me-4 rounded">
                                        <div class="text">
                                            <h4>{{ post.title }}</h4>
                                            <div class="post-meta">
                                                <span class="mr-2">{{ post.created }} </span>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>


                </div> <!-- /.widget -->
            </div> <!-- /.col-lg-4 -->
        </div> <!-- /.row -->

        <div class="row mt-5">
            <div class="col-12 text-center">
      <!--
          **==========
          NOTE:
          Please don't remove this copyright link unless you buy the license here https://untree.co/license/
          **==========
        -->

        <p>Copyright &copy;<script>document.write(new Date().getFullYear());</script>. All Rights Reserved. &mdash; Designed with love by <a href="https://untree.co">Untree.co</a> <!-- License information: https://untree.co/license/ -->
        </p>
      </div>
    </div>
  </div> <!-- /.container -->
</footer> <!-- /.site-footer -->

blog/templates/blog/_nav.html
    <div class="site-mobile-menu site-navbar-target">
		<div class="site-mobile-menu-header">
			<div class="site-mobile-menu-close">
				<span class="icofont-close js-menu-toggle"></span>
			</div>
		</div>
		<div class="site-mobile-menu-body"></div>
	</div>

    <nav class="site-nav">
		<div class="container">
			<div class="menu-bg-wrap">
				<div class="site-navigation">
					<div class="row g-0 align-items-center">
						<div class="col-2">
							<a href="{% url 'blog:homepage' %}" class="logo m-0 float-start">Blogy<span class="text-primary">.</span></a>
						</div>
						<div class="col-8 text-center">
							<form action="#" class="search-form d-inline-block d-lg-none">
								<input type="text" class="form-control" placeholder="Search...">
								<span class="bi-search"></span>
							</form>
                        {% load mptt_tags %}
                            <ul class="js-clone-nav d-none d-lg-inline-block text-start site-menu mx-auto">
                                <li class="active"><a href="{% url 'blog:homepage' %}">Home</a></li>
                                {% recursetree categories %}
                                    <li class="has-children">
                                        <a href="{{ node.get_absolute_url }}">{{ node.name }}</a>
                                        {% if not node.is_leaf_node %}
                                            <ul class="dropdown">
                                                {{ children }}
                                            </ul>
                                        {% endif %}
                                    </li>
                                {% endrecursetree %}
                            </ul>

						</div>
						<div class="col-2 text-end">
							<a href="#" class="burger ms-auto float-end site-menu-toggle js-menu-toggle d-inline-block d-lg-none light">
								<span></span>
							</a>
							<form action="{% url 'blog:search_results' %}" method="get" class="search-form d-none d-lg-inline-block">
								<input type="text" class="form-control" placeholder="Search..." name="q">
								<span class="bi-search"></span>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</nav>

blog/templates/blog/category.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    	<div class="section search-result-wrap">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="heading">Category: {{ title }}</div>
				</div>
			</div>
			<div class="row posts-entry">
				<div class="col-lg-12">
                    {% for post in posts %}
                        <div class="blog-entry d-flex blog-entry-search-item">
                            <a href="{{ post.get_absolute_url }}" class="img-link me-4">
                                <img src="{{ post.image.url }}" alt="Image" class="img-fluid">
                            </a>
                            <div>
                                <span class="date">{{ post.created }} &bullet; <a href="#">{{ post.category.name }}</a></span>
                                <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                                <p>{{ post.content|safe|linebreaks|truncatewords:30 }}</p>
                                <p><a href="{{ post.get_absolute_url }}" class="btn btn-sm btn-outline-primary">Read More</a></p>
                            </div>
                        </div>
                    {% endfor %}

                    <div class="row text-start pt-5 border-top">
						<div class="col-md-12">
							<div class="custom-pagination">
                                {% if page_obj.has_other_pages %}
                                  <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                                    {% else %}
                                      <li class="disabled"><span>&laquo;</span></li>
                                    {% endif %}
                                    {% for i in page_obj.paginator.page_range %}
                                      {% if page_obj.number == i %}
                                        <li class="active"><span>{{ i }} </span></li>
                                      {% else %}
                                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                                      {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                                    {% else %}
                                      <li class="disabled"><span>&raquo;</span></li>
                                            {% endif %}
                                  </ul>
                                {% endif %}
                            </div>
						</div>
					</div>

				</div>
			</div>
		</div>
	</div>
{% endblock %}

blog/templates/blog/comment.html
{% extends "base.html" %}

{% block title %}Add a comment{% endblock %}

{% block content %}
    {% if comment %}
        <h2>Your comment has been added.</h2>
        <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
    {% else %}
        {% include "blog/comment_form.html" %}
{% endif %}
{% endblock %}

blog/templates/blog/comment_form.html
<h2>Add a new comment</h2>

<div class="comment-form-wrap pt-5">
    <form action="{% url "blog:post_comment" post.id %}" method="post" class="p-5 bg-light">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Add comment" class="btn btn-primary"></p>
    </form>
</div>

blog/templates/blog/homepage.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}

{% block title %}{% endblock %}

{% block content %}

    <!-- Start retroy layout blog posts -->
	<section class="section bg-light">
		<div class="container">
			<div class="row align-items-stretch retro-layout">
				<div class="col-md-4">
                    {% show_latest_posts_by_cat count=2 category='business' position='horizontal' %}
				</div>
				<div class="col-md-4">
					{% show_latest_posts_by_cat count=1 category='sport' position='vertical' %}
				</div>
				<div class="col-md-4">
			        {% show_latest_posts_by_cat count=2 category='programming' %}
				</div>
			</div>
		</div>
	</section>
	<!-- End retroy layout blog posts -->

    <!-- Start posts-entry -->
	<section class="section posts-entry">
		<div class="container">
			<div class="row mb-4">
				<div class="col-sm-6">
					<h2 class="posts-entry-title">Business</h2>
				</div>
				<div class="col-sm-6 text-sm-end"><a href="./category/business" class="read-more">View All</a></div>
			</div>
			{% show_latest_posts_by_cat_2_3 category='business' %}
		</div>
	</section>
	<!-- End posts-entry -->

    	<!-- Start posts-entry -->
	<section class="section posts-entry posts-entry-sm bg-light">
		<div class="container">
			<div class="row">
				{% latest_posts_4_row %}
			</div>
		</div>
	</section>
	<!-- End posts-entry -->

    	<!-- Start posts-entry -->
	<section class="section posts-entry">
		<div class="container">
			<div class="row mb-4">
				<div class="col-sm-6">
					<h2 class="posts-entry-title">Programming</h2>
				</div>
				<div class="col-sm-6 text-sm-end"><a href="./category/programming" class="read-more">View All</a></div>
			</div>
			{% show_latest_posts_by_cat_2_3 category='programming' position='left' %}
		</div>
	</section>

    <section class="section">
        <div class="container">

            <div class="row mb-4">
                <div class="col-sm-6">
                    <h2 class="posts-entry-title">Sport</h2>
                </div>
                <div class="col-sm-6 text-sm-end"><a href="./category/sport" class="read-more">View All</a></div>
            </div>

            <div class="row">
                {% show_latest_posts_by_cat_3_row category='sport' %}
            </div>

        </div>
    </section>

    <div class="section bg-light">
        <div class="container">

            <div class="row mb-4">
                <div class="col-sm-6">
                    <h2 class="posts-entry-title">Travel</h2>
                </div>
                <div class="col-sm-6 text-sm-end"><a href="./category/sport" class="read-more">View All</a></div>
            </div>

            <div class="row align-items-stretch retro-layout-alt">

                {% latest_posts_by_cat_masonry category='sport' %}

            </div>

        </div>
    </div>
{% endblock %}

blog/templates/blog/latest_posts.html
{% for post in latest_posts %}
    <a href="{{ post.get_absolute_url }}" class="h-entry {% if position == 'horizontal' %}mb-30 v-height{% else %}img-5 h-100 {% endif %} gradient">

        <div class="featured-img" style="background-image: url('{{ post.image.url }}');"></div>
        <img src="{{ post.image.url }}">
        <div class="text">
            <span class="date">{{ post.created }}</span>
        </div>
    </a>
{% endfor %}

blog/templates/blog/latest_posts_4_row.html
{% for post in latest_posts %}
    <div class="col-md-6 col-lg-3">
        <div class="blog-entry">
            <a href="{{ post.get_absolute_url }}" class="img-link">
                <img src="{{ post.image.url }}" alt="Image" class="img-fluid">
            </a>
            <span class="date">{{ post.created }}</span>
            <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
            <p>{{ post.content|safe|linebreaks|truncatewords:15 }}</p>
            <p><a href="{{ post.get_absolute_url }}" class="read-more">Continue Reading</a></p>
        </div>
    </div>
{% endfor %}

blog/templates/blog/latest_posts_by_cat_2_3.html
<div class="row g-3">
    <div class="col-md-9 {% if position == 'left' %}order-md-2{% endif %}">
        <div class="row g-3">
            {% for post in latest_posts_2 %}
            <div class="col-md-6">
                <div class="blog-entry">
                    <a href="{{ post.get_absolute_url }}" class="img-link">
                        <img src="{{ post.image.url }}" alt="Image" class="img-fluid">
                    </a>
                    <span class="date">{{ post.created }}</span>
                    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                    <p>{{ post.content|safe|linebreaks|truncatewords:50 }}</p>
                    <p><a href="{{ post.get_absolute_url }}" class="btn btn-sm btn-outline-primary">Read More</a></p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="col-md-3">
        <ul class="list-unstyled blog-entry-sm">
            {% for post in latest_posts_3 %}
                <li>
                    <span class="date">{{ post.created }}</span>
                    <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                    <p>{{ post.content|safe|linebreaks|truncatewords:15 }}</p>
                    <p><a href="{{ post.get_absolute_url }}" class="read-more">Continue Reading</a></p>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <div class="site-cover site-cover-sm same-height overlay single-page"
         style="background-image: url('{% static "images/hero_5.jpg" %}');">
        <div class="container">
            <div class="row same-height justify-content-center">
                <div class="col-md-6">
                    <div class="post-entry text-center">
                        <h1 class="mb-4">{{ post.title }}</h1>
                        <div class="post-meta align-items-center text-center">
                            <figure class="author-figure mb-0 me-3 d-inline-block"><img
                                    src="{% static 'images/person_4.jpg' %}" alt="Image" class="img-fluid"></figure>
                            <span class="d-inline-block mt-1">By {{ post.author }}</span>
                            <span>{{ post.created }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <section class="section">
        <div class="container">

            <div class="row blog-entries element-animate">

                <div class="col-md-12 col-lg-8 main-content">

                    <div class="post-content-body">
                        <div class="row my-4">
                            <div class="col-md-12 mb-4">
                                <img src="{{ post.image.url }}" alt="Image placeholder" class="img-fluid rounded">
                            </div>
                        </div>
                        <p>{{ post.content|safe|linebreaks }}</p>
                    </div>


                    <div class="pt-5">
                        <p>Categories: <a href="#">Food</a>, <a href="#">Travel</a> Tags: <a href="#">#manila</a>, <a
                                href="#">#asia</a></p>
                    </div>


                    <div class="pt-5 comment-wrap">
                        {% with comments.count as total_comments %}
                            <h3 class="mb-5 heading">
                                {{ total_comments }} comment{{ total_comments|pluralize }}
                            </h3>
                        {% endwith %}
                        <ul class="comment-list">
                            {% for comment in comments %}
                                <li class="comment">
                                <div class="comment-body">
                                    <h3>{{ comment.name }}</h3>
                                    <div class="meta">{{ comment.created }}</div>
                                    <p>{{ comment.body|linebreaks }}</p>
                                </div>
                            {% empty %}
                                <p>There are no comments.</p>
                            {% endfor %}
                        </ul>
                        {% include "blog/comment_form.html" %}


                    </div>

                </div>

                <!-- END main-content -->

                <div class="col-md-12 col-lg-4 sidebar">
                    <div class="sidebar-box">
                        <h3 class="heading">Popular Posts</h3>
                        <div class="post-entry-sidebar">
                            <ul>
                                {% for p_post in popular_posts %}
                                    <li>
                                        <a href="{{ p_post.get_absolute_url }}">
                                            <img src="{{ p_post.image.url }}" alt="Image placeholder"
                                                 class="me-4 rounded">
                                            <div class="text">
                                                <h4>{{ p_post.title }}</h4>
                                                <div class="post-meta">
                                                    <span class="mr-2">{{ p_post.created }} </span>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <!-- END sidebar-box -->

                    <div class="sidebar-box">
                        <h3 class="heading">Categories</h3>
                        <ul class="categories">
                            {% for category, post_count in subcategory_post_counts.items %}
                                {% if forloop.counter <= 10 %}
                                    <li><a href="{{ category.get_absolute_url }}">{{ category.name }}
                                        <span>({{ post_count }})</span></a></li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                    <!-- END sidebar-box -->

                    <div class="sidebar-box">
                        <h3 class="heading">Tags</h3>
                        <ul class="tags">
                            {% for tag in post.tags.all %}
                                <li><a href="{% url 'blog:posts_by_tag' tag.slug %}">{{ tag.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <!-- END sidebar -->

            </div>
        </div>
    </section>


    <!-- Start posts-entry -->
    <section class="section posts-entry posts-entry-sm bg-light">
        <div class="container">
            <div class="row mb-4">
                <div class="col-12 text-uppercase text-black">More Blog Posts</div>
            </div>
            <div class="row">
                {% latest_posts_4_row %}
            </div>
        </div>
    </section>
    <!-- End posts-entry -->


{% endblock %}